package com.lapots.breed.judge.domain

import com.openpojo.validation.Validator
import com.openpojo.validation.ValidatorBuilder
import com.openpojo.validation.rule.impl.EqualsAndHashCodeMatchRule
import com.openpojo.validation.test.impl.GetterTester
import com.openpojo.validation.test.impl.SetterTester
import nl.jqno.equalsverifier.EqualsVerifier
import org.junit.Test

class PojoTest {
    @Test
    void validate() {
        Validator validator = ValidatorBuilder.create()
                // don't setter/getter rules because they are generated by lombok so don't exist
                .with(new EqualsAndHashCodeMatchRule())
                .with(new SetterTester(), new GetterTester())
                .build()
        validator.validate("com.lapots.breed.judge.domain")
    }

    @Test
    void validateEquals() {
        EqualsVerifier.forClass(Player.class).verify()
        EqualsVerifier.forClass(PlayerLevel.class).verify()
    }
}
